# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
#
# IMPORTANTE: Este archivo contiene la configuración de hardware específica
# del servidor Turing. Solo regenerar si cambias:
# - Discos/particiones
# - Motherboard
# - Tipo de boot (BIOS/UEFI)
#
# Hardware detectado:
# - CPU: Intel (con microcode updates)
# - Storage: NVMe + AHCI
# - Boot: UEFI (systemd-boot)
# - Generado: 2026-01-14
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod"];
    initrd.kernelModules = [];
    kernelModules = [];
    extraModulePackages = [];
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/b9410063-7088-49a5-a800-e2334e1b13fc";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/BEBD-37AF";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/28601dd1-39cf-48f1-becb-9eba9981cbac";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
